export const FIELDS = [
  { def: 1, en: "", weight: 0, show: true, nl: "adres_aantal_brp_adres" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_aantal_verschillende_wijken" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_aantal_verzendadres" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_aantal_woonadres_handmatig" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_dagen_op_adres" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentst_onderdeel_rdam" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_buurt_groot_ijsselmonde" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_buurt_nieuwe_westen" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_buurt_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_buurt_oude_noorden" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_buurt_vreewijk" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_plaats_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_plaats_rotterdam" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_wijk_charlois" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_wijk_delfshaven" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_wijk_feijenoord" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_wijk_ijsselmonde" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_wijk_kralingen_c" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_wijk_noord" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_wijk_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_wijk_prins_alexa" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_recentste_wijk_stadscentru" },
  { def: 0, en: "", weight: 0, show: true, nl: "adres_unieke_wijk_ratio" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_aanmelding_afgesloten" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_aantal_woorden" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_afgelopen_jaar_afsprakenplan" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "afspraak_afgelopen_jaar_monitoring_insp__wet_taaleis_na_12_mnd_n_a_v__taa04_____geen_maatregel",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_afgelopen_jaar_ontheffing" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_afgelopen_jaar_ontheffing_taaleis" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_afgelopen_jaar_plan_van_aanpak" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "afspraak_afgelopen_jaar_signaal_voor_medewerker",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "afspraak_afgelopen_jaar_vervolgmeting_matchbaarheid_werkzoekende_klant",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "afspraak_afgelopen_jaar_voortgang_aanmelding_en_deelname",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_afsprakenplan" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_controle_aankondiging_maatregel" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_controle_verwijzing" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_deelname_compleet_uit_webapplicatie" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_galo_gesprek" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_gespr__einde_zoekt___galo_gesprek_" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_inspanningsperiode" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_laatstejaar_aantal_woorden" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_laatstejaar_resultaat_ingevuld" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "afspraak_laatstejaar_resultaat_ingevuld_uniek",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_participatietrede_vervolgmeting" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_resultaat_ingevuld_uniek" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_signaal_van_aanbieder" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_signaal_voor_medewerker" },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_toevoegen_inschrijving_uwvwb" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "afspraak_vervolgmeting_matchbaarheid_werkzoekende_klant",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "afspraak_verzenden_beschikking_i_v_m__niet_voldoen_aan_wet_taaleis",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "afspraak_voortgangsgesprek" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_aantal_huidig" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_dagen_financiele_problemen" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_dagen_lichamelijke_problematiek" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_dagen_psychische_problemen" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_financiele_problemen" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_hist_lichamelijke_problematiek" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_hist_psychische_problemen" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "belemmering_hist_stabiele_mix__sz____dagbesteding_werk",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_hist_taal" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_hist_verslavingsproblematiek" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_ind" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_ind_hist" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_niet_computervaardig" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_psychische_problemen" },
  { def: 0, en: "", weight: 0, show: true, nl: "belemmering_woonsituatie" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "beschikbaarheid_aantal_historie_afwijkend_wegens_medische_omstandigheden",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "beschikbaarheid_aantal_historie_afwijkend_wegens_sociaal_maatschappelijke_situatie",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "beschikbaarheid_huidig_afwijkend_wegens_medische_omstandigheden",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "beschikbaarheid_huidig_bekend" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "beschikbaarheid_recent_afwijkend_wegens_medische_omstandigheden",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "beschikbaarheid_recent_afwijkend_wegens_sociaal_maatschappelijke_situatie",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_aansturen" },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_analyseren" },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_ethisch_en_integer_handelen" },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_formuleren_en_rapporteren" },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_gedrevenheid_en_ambitie_tonen" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "competentie_instructies_en_procedures_opvolgen",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_kwaliteit_leveren" },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_leren" },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_materialen_en_middelen_inzetten" },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_met_druk_en_tegenslag_omgaan" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "competentie_omgaan_met_verandering_en_aanpassen",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_onderzoeken" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "competentie_op_de_behoeften_en_verwachtingen_van_de__klant__richten",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_overtuigen_en_beïnvloeden" },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_plannen_en_organiseren" },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_samenwerken_en_overleggen" },
  { def: 0, en: "", weight: 0, show: true, nl: "competentie_vakdeskundigheid_toepassen" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp__arbeids_motivatie" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp__pre__intake" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp__werk_intake" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_arbeidsdiagnose_dariuz" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_beoordelen_taaleis" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean__arbeids_motivatie",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean__pre__intake" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean__werk_intake" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_beoordelen_taaleis",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_contact_derden" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_contact_met_aanbieder",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_diagnosegesprek" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_documenten__innemen_",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_documenttype__cv_",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_documenttype__diploma_s_en_certificaten_",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_documenttype__overeenkomst_",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_financiële_situatie",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_groepsbijeenkomst",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_inkomen" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_maatregel_overweging",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_match___werk" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_matching" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_motivatie" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_mutatie" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_no_show" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_overige" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_overleg_met_inkomen",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_scholing" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_sollicitatie" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_taaleis___voldoet",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_terugbelverzoek" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_traject" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_uitnodiging" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_boolean_ziek__of_afmelding",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_boolean_zorg" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_contact_derden" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_contact_met_aanbieder" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_diagnosegesprek" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_documenten__innemen_" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_documenttype__cv_" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_documenttype__overeenkomst_",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_financiële_situatie" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_groepsbijeenkomst" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_inkomen" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_inname_aanvraag" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_inspanningstoets" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_maatregel_overweging" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_matching" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_mutatie" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_no_show" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_overige" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_overleg_met_inkomen" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_quickscan" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_scholing" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_screening" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_terugbelverzoek" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_traject" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_uitnodiging" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_vakantie" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_onderwerp_werkintake__niet_verschenen",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_ziek__of_afmelding" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_onderwerp_zorg" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_afgelopenjaar_anders" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_soort_afgelopenjaar_document__inkomend_",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_soort_afgelopenjaar_document__uitgaand_",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_soort_afgelopenjaar_e_mail__inkomend_",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_soort_afgelopenjaar_e_mail__uitgaand_",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_afgelopenjaar_gesprek" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_soort_afgelopenjaar_gesprek_op_locatie",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_afgelopenjaar_rapportage_rib" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_soort_afgelopenjaar_telefoontje__inkomend_",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "contacten_soort_afgelopenjaar_telefoontje__uitgaand_",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_anders" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_document__inkomend_" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_document__uitgaand_" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_e_mail__inkomend_" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_e_mail__uitgaand_" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_gesprek_op_locatie" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_groepsbijeenkomsten" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_rapportage_deelname" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_rapportage_rib" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_telefoontje__inkomend_" },
  { def: 0, en: "", weight: 0, show: true, nl: "contacten_soort_telefoontje__uitgaand_" },
  { def: 0, en: "", weight: 0, show: true, nl: "deelname_act_actueel_projecten_uniek" },
  { def: 0, en: "", weight: 0, show: true, nl: "deelname_act_hist_projecten_niet_gestart" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "deelname_act_reintegratieladder_ondersteunende_instrumenten",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "deelname_act_reintegratieladder_werk_re_integratie",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "instrument_aantal_laatstejaar" },
  { def: 0, en: "", weight: 0, show: true, nl: "instrument_ladder_historie_activering" },
  { def: 0, en: "", weight: 0, show: true, nl: "instrument_ladder_historie_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "instrument_ladder_huidig_activering" },
  { def: 0, en: "", weight: 0, show: true, nl: "instrument_ladder_huidig_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "instrument_ladder_huidig_werk_re_integratie" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_centrale_actie_wigo4it",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_diagnose_gesteld",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_direct_matchbaar",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_doelstelling_bereikt__geen_uitstroom",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_doelstelling_bereikt__uitstroom_naar_regulier_werk",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_doelstelling_bereikt__uitstroom_overig",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_doelstelling_niet_bereikt__geen_uitstroom",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_niet_matchbaar",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_niet_succesvol",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_niet_succesvol__reden_bij_werkzoekende",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_op_termijn_matchbaar",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "instrument_reden_beeindiging_historie_other" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_overdracht_naar_mo",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_overdracht_naar_prematching",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_overdracht_naar_regulier_team_iwpm",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_overdracht_succesvol",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_succesvol",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_succesvol__doelstelling_bereikt",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_uitval__aanbod_niet_langer_zinvol_volgens_gemeente",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "instrument_reden_beeindiging_historie_uitval__klant_wz__ziet_af_van_aanbod",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "ontheffing_actueel_ind" },
  { def: 0, en: "", weight: 0, show: true, nl: "ontheffing_dagen_hist_mean" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "ontheffing_dagen_hist_vanwege_uw_medische_omstandigheden",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "ontheffing_hist_ind" },
  { def: 0, en: "", weight: 0, show: true, nl: "ontheffing_reden_hist_medische_gronden" },
  { def: 0, en: "", weight: 0, show: true, nl: "ontheffing_reden_hist_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "ontheffing_reden_hist_sociale_gronden" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "ontheffing_reden_hist_tijdelijke_ontheffing_arbeidsverpl__en_tegenprestatie",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "ontheffing_reden_hist_tijdelijke_ontheffing_arbeidsverplichtingen",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "ontheffing_reden_hist_vanwege_uw_sociaal_maatschappelijke_situatie",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "ontheffing_reden_tijdelijke_ontheffing_arbeidsverpl__en_tegenprestatie",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "persoon_geslacht_vrouw" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoon_leeftijd_bij_onderzoek" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_communicatie_opm" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_dagen_sinds_opvoer",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_dagen_sinds_taaleis",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_doorzettingsvermogen_opm",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_flexibiliteit_opm" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_hobbies_sport" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_houding_opm" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_ind_activering_traject",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_ind_buiten_kantoortijden",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_ind_regulier_arbeidsritme",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_initiatief_opm" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_leergierigheid_opm",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_motivatie_opm" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_nl_begrijpen3" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_nl_lezen3" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_nl_lezen4" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_nl_schrijven0" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_nl_schrijven1" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_nl_schrijven2" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_nl_schrijven3" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_nl_schrijvenfalse" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_nl_spreken1" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_nl_spreken2" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_nl_spreken3" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_opstelling" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_overige_opmerkingen",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_presentatie_opm" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_spreektaal" },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_spreektaal_anders" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_taaleis_schrijfv_ok",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "persoonlijke_eigenschappen_taaleis_voldaan" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_uiterlijke_verzorging_opm",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_uitstroom_verw_vlgs_klant",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_uitstroom_verw_vlgs_km",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "persoonlijke_eigenschappen_zelfstandigheid_opm",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_actueel_pla_categorie_doelstelling_16" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_actueel_pla_categorie_doelstelling_9" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_einde_doelstelling_bereikt" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "pla_einde_doelstelling_bereikt__nieuw_trajectplan",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_einde_doelstelling_bereikt__overdracht" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_einde_doelstelling_niet_bereikt" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "pla_einde_doelstelling_niet_bereikt__nieuw_trajectplan",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "pla_einde_doelstelling_niet_bereikt__overdracht",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "pla_einde_geplande_einddatum_overschreden_zonder_nader_bericht",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_einde_other" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "pla_einde_uitstroom_anders_dan_volgen_onderwijs__regulier_werk_of_als_zelfstandige",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_1" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_10" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_11" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_16" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_2" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_27" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_3" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_4" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_5" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_6" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_9" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_hist_pla_categorie_doelstelling_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_historie_maatschappelijke_inspanning" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_historie_ontwikkeling" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_historie_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_historie_werk" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_historie_werk_en_inburgering" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_ondertekeningen_actueel" },
  { def: 0, en: "", weight: 0, show: true, nl: "pla_ondertekeningen_historie" },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_kind_basisschool_kind" },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_kind_heeft_kinderen" },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_kind_huidige_aantal" },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_kind_jongvolwassen" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "relatie_kind_leeftijd_verschil_ouder_eerste_kind",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_kind_tiener" },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_kind_volwassen" },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_overig_actueel_vorm__gemachtigde" },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_overig_actueel_vorm__kostendeler" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "relatie_overig_actueel_vorm__onderhoudsplichtige",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "relatie_overig_actueel_vorm__ouders_verzorgers",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_overig_actueel_vorm_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_overig_bewindvoerder" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "relatie_overig_historie_vorm__andere_inwonende",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_overig_historie_vorm__gemachtigde" },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_overig_historie_vorm__kostendeler" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "relatie_overig_historie_vorm__onderhoudsplichtige",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_overig_kostendeler" },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "relatie_partner_aantal_partner___partner__gehuwd_",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "relatie_partner_aantal_partner___partner__ongehuwd_",
  },
  {
    def: 0,
    en: "",
    weight: 0,
    show: true,
    nl: "relatie_partner_huidige_partner___partner__gehuwd_",
  },
  { def: 0, en: "", weight: 0, show: true, nl: "relatie_partner_totaal_dagen_partner" },
  { def: 0, en: "", weight: 0, show: true, nl: "typering_aantal" },
  { def: 0, en: "", weight: 0, show: true, nl: "typering_dagen_som" },
  { def: 0, en: "", weight: 0, show: true, nl: "typering_hist_aantal" },
  { def: 0, en: "", weight: 0, show: true, nl: "typering_hist_inburgeringsbehoeftig" },
  { def: 0, en: "", weight: 0, show: true, nl: "typering_hist_ind" },
  { def: 0, en: "", weight: 0, show: true, nl: "typering_hist_sector_zorg" },
  { def: 0, en: "", weight: 0, show: true, nl: "typering_ind" },
  { def: 0, en: "", weight: 0, show: true, nl: "typering_indicatie_geheime_gegevens" },
  { def: 0, en: "", weight: 0, show: true, nl: "typering_other" },
  { def: 0, en: "", weight: 0, show: true, nl: "typering_transport__logistiek___tuinbouw" },
  { def: 0, en: "", weight: 0, show: true, nl: "typering_zorg__schoonmaak___welzijn" },
];
